// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .proto

// Protobuf Java Version: 3.25.1
package su.foxogram.protos;

public interface ImageMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foxoproto.ImageMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type = 1;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>bytes bytes = 2;</code>
   * @return The bytes.
   */
  com.google.protobuf.ByteString getBytes();
}
