// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .proto

// Protobuf Java Version: 3.25.1
package su.foxogram.protos;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foxoproto_ImageMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foxoproto_ImageMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foxoproto_ProtoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foxoproto_ProtoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\006.proto\022\tfoxoproto\"+\n\014ImageMessage\022\014\n\004t" +
      "ype\030\001 \001(\005\022\r\n\005bytes\030\002 \001(\014\"5\n\014ProtoMessage" +
      "\022\017\n\007content\030\001 \001(\t\022\024\n\014access_token\030\002 \001(\tB" +
      "\036\n\022su.foxogram.protosB\006ProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foxoproto_ImageMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foxoproto_ImageMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foxoproto_ImageMessage_descriptor,
        new java.lang.String[] { "Type", "Bytes", });
    internal_static_foxoproto_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foxoproto_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foxoproto_ProtoMessage_descriptor,
        new java.lang.String[] { "Content", "AccessToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
