// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .proto

// Protobuf Java Version: 3.25.1
package su.foxogram.protos;

public interface ProtoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foxoproto.ProtoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string access_token = 2;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 2;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();
}
